groups:
  - name: shelly_trends
    rules:
      # Energy consumption rates
      - record: shelly_energy_consumption_rate_kwh_per_hour
        expr: rate(shelly_energy_total_watthours[1h]) * 3600 / 1000
        labels:
          trend_type: "consumption_rate"

      - record: shelly_energy_consumption_daily_kwh
        expr: increase(shelly_energy_total_watthours[24h]) / 1000
        labels:
          trend_type: "daily_consumption"

      - record: shelly_energy_consumption_weekly_kwh
        expr: increase(shelly_energy_total_watthours[7d]) / 1000
        labels:
          trend_type: "weekly_consumption"

      # Power trends
      - record: shelly_power_avg_5m
        expr: avg_over_time(shelly_power_watts[5m])
        labels:
          trend_type: "power_average"

      - record: shelly_power_avg_1h
        expr: avg_over_time(shelly_power_watts[1h])
        labels:
          trend_type: "power_average"

      - record: shelly_power_max_1h
        expr: max_over_time(shelly_power_watts[1h])
        labels:
          trend_type: "power_maximum"

      # Efficiency and balance metrics
      - record: shelly_phase_balance_ratio
        expr: |
          (
            max(shelly_power_watts{meter=~"phase_.*"}) - 
            min(shelly_power_watts{meter=~"phase_.*"})
          ) / 
          max(shelly_power_watts{meter=~"phase_.*"})
        labels:
          trend_type: "phase_balance"

      # Cost estimation (assuming 0.15 EUR/kWh)
      - record: shelly_daily_cost_eur
        expr: increase(shelly_energy_total_watthours[24h]) / 1000 * 0.15
        labels:
          trend_type: "cost_estimation"
          currency: "EUR"
