name: Device Support Request
description: Request support for a new Shelly device
title: "[DEVICE] "
labels: ["device-support", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for requesting support for a new Shelly device! This helps us expand compatibility.

  - type: input
    id: device_model
    attributes:
      label: Device Model
      description: What Shelly device model do you want supported?
      placeholder: "e.g., Shelly Plus 1PM, Shelly Pro 4PM, Shelly EM"
    validations:
      required: true

  - type: dropdown
    id: api_type
    attributes:
      label: API Type
      description: What API does this device use?
      options:
        - RPC API (newer devices)
        - Legacy HTTP API (older devices)
        - Unknown
    validations:
      required: true

  - type: textarea
    id: capabilities
    attributes:
      label: Device Capabilities
      description: What capabilities does this device have?
      placeholder: |
        - Power monitoring (single/three-phase)
        - Relay control
        - Temperature monitoring
        - Energy monitoring
        - WiFi status
        - Cloud connectivity
    validations:
      required: true

  - type: textarea
    id: metrics
    attributes:
      label: Desired Metrics
      description: What metrics would you like to collect from this device?
      placeholder: |
        - Power consumption
        - Relay state
        - Temperature
        - Energy totals
        - Device status

  - type: input
    id: firmware_version
    attributes:
      label: Firmware Version
      description: What firmware version is the device running?
      placeholder: "e.g., 1.0.0"

  - type: textarea
    id: api_response
    attributes:
      label: API Response Sample
      description: Please provide a sample API response (remove sensitive data)
      render: json
      placeholder: |
        {
          "id": 1,
          "result": {
            "sys": {
              "mac": "AA:BB:CC:DD:EE:FF",
              "restart_required": false,
              "time": "12:34:56",
              "unixtime": 1234567890,
              "uptime": 12345,
              "ram_size": 262144,
              "ram_free": 123456,
              "fs_size": 458752,
              "fs_free": 234567,
              "cfg_rev": 5
            }
          }
        }

  - type: textarea
    id: testing
    attributes:
      label: Testing Availability
      description: Are you able to test the implementation?
      placeholder: "I have this device and can help test the implementation"

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this device isn't already requested
          required: true
        - label: I have provided all the information requested above
          required: true
        - label: I am willing to help test the implementation
