version: "3.8"

services:
  shelly-exporter:
    image: ghcr.io/aimar/shelly-prometheus-exporter:latest
    container_name: shelly-exporter
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/etc/shelly-exporter/config.yaml:ro
    environment:
      - TZ=UTC
    command: ["--config=/etc/shelly-exporter/config.yaml"]
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - shelly-network

networks:
  shelly-network:
    driver: bridge
