name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  GO_VERSION: "1.24"

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        run: CGO_ENABLED=0 go test -v ./...

      - name: Run race detector
        run: CGO_ENABLED=1 go test -race -v ./...
        continue-on-error: true

      - name: Run coverage
        run: CGO_ENABLED=0 go test -coverprofile=coverage.out -covermode=atomic ./...

      - name: Prepare coverage for Qlty
        run: sed 's|github.com/aimar/shelly-prometheus-exporter/||g' coverage.out > coverage_relative.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Upload coverage to Qlty
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage_relative.out
          validate: false

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5.0

  # codeclimate:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Go
  #       uses: actions/setup-go@v6
  #       with:
  #         go-version: ${{ env.GO_VERSION }}

  #     - name: CodeClimate Analysis
  #       uses: paambaati/codeclimate-action@v4.0.0
  #       with:
  #         coverageCommand: make test-coverage
  #         coverageLocations: coverage.out:lcov
  #       env:
  #         CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  #       continue-on-error: true

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags "-X main.version=${{ github.ref_name }} -X main.commit=${{ github.sha }} -X main.buildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ)" -o shelly-exporter-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/shelly-exporter

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shelly-exporter-${{ matrix.goos }}-${{ matrix.goarch }}
          path: shelly-exporter-${{ matrix.goos }}-${{ matrix.goarch }}
